### ISSUE TITLE
initial template loses data context when animating

### ISSUE THREAD

**Issue by funkyeah** [percolatestudio/momentum-iron-router#11]
When transitioning from one route to the next the data populated in the initial page is disappears, causing some glitchy behavior. Would it be possible to solve this, maybe with [subs-manger](https://github.com/meteorhacks/subs-manager) integration?

**Comment by funkyeah** [comment]
@tmeasday or @zol, sorry to bother, but any thoughts on this?

looking through the code I did notice that it might be using [Router.current().path](https://github.com/percolatestudio/momentum-iron-router/blob/master/momentum-iron-router.js#L12) and [Router.current().options.initiator](Router.current().options.initiator), neither of which are valid in the latest iron-router... I'm not even sure what initiator is supposed to be

I'd be more than happy to do the legwork if someone could point me in the right direction

**Comment by tmeasday** [comment]
@funkyeah this shouldn't happen because what occurs is the following:

1. Routing happens, IR decides the page needs to come off the screen. Tells blaze so. At the same time, cancels the relevant subscriptions etc.
2. Blaze, knowing the page is coming off the screen, kills reactivity inside it. It asks momentum (via uihooks) to take the element off the screen.
3. Momentum doesn't immediately take the page off the screen, but instead starts transitioning it off (or whatever) and some time later removes it.

If you are seeing different behaviour it's probably for a different reason. There are a lot of subtleties involved unfortunately.

As a educated guess: are you using a separate loading page? If so, is it possible that you are immediately transitioning to loading, then some # of ms later, trying to transition to the new page while the loading page is still making it's way onto the screen? I've seen this lead to behaviour similar that looks like what you are describing.

If not, can you put together a minimal reproduction and I can take a look.

**Comment by funkyeah** [comment]
The app itself is actually fairly minimal beer menu app you are free to check out:
https://github.com/The3vilMonkey/BrewsOnTap

At any rate thanks a million for the description of how things work. It immediately put me on the right track. While I am using a loading template that is through iron router and behaves just fine.

What it ended up being is the data context I was depending on. For the failing route I wasn't passing the data context with iron router but more or less with a Session variable. The Session variable was managed in iron-router (cleared at onStop), which was causing the loss of data context.

Anyway, thanks again. I do think the above description would be useful in the README. If you agree I'd be happy to add it after my first pull-request is accepted or denied.
